### ISSUE TITLE
Chapter 11 - itunes-search erroring

### ISSUE THREAD

**Issue by denizcift** [ErikCH/VuejsInActionCode#19]
I am having below error in browser even though I installed all dependencies and created files in order in vuetify/  i-tunes project:
Error
Module build failed (from ./node_modules/stylus-loader/index.js): Error: C:\Users\deniz\Documents\vuejs in action\itunes-search\assets\app.styl:3:10 1| 2| // Import Vuetify styling 3| @require '~vuetify/src/stylus/main' ---------------^ failed to locate @require file ~vuetify/src/stylus/main.styl at CachedPathEvaluator.visitImport (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\stylus-loader\lib\evaluator.js:157:21) at CachedPathEvaluator.Visitor.visit (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\stylus\lib\visitor\index.js:28:40) at CachedPathEvaluator.Evaluator.visit (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\stylus\lib\visitor\evaluator.js:160:18) at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\stylus\lib\visitor\evaluator.js:707:27) at CachedPathEvaluator.Visitor.visit (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\stylus\lib\visitor\index.js:28:40) at CachedPathEvaluator.Evaluator.visit (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\stylus\lib\visitor\evaluator.js:160:18) at CachedPathEvaluator.Evaluator.evaluate (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\stylus\lib\visitor\evaluator.js:247:15) at Renderer.render (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\stylus\lib\renderer.js:86:26) at C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\stylus-loader\index.js:167:12 at tryCatchReject (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\when\lib\makePromise.js:840:30) at runContinuation1 (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\when\lib\makePromise.js:799:4) at Fulfilled.when (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\when\lib\makePromise.js:590:4) at Pending.run (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\when\lib\makePromise.js:481:13) at Scheduler._drain (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\when\lib\Scheduler.js:62:19) at Scheduler.drain (C:\Users\deniz\Documents\vuejs in action\itunes-search\node_modules\when\lib\Scheduler.js:27:9) at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by dmn-ai** [comment]
Vuetify no longer supports Stylus since version 2.0.0.  I was fixing issue after issue, when instead I should have done this from the start, when you install vuetify with npm install vuetify, do this instead.   npm install vuetify@1.5.24
